// <auto-generated />
using System;
using MLDShopping_Admin.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MLDShopping_Admin.Migrations
{
    [DbContext(typeof(CMSShoppingContext))]
    partial class CMSShoppingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MLDShopping_Admin.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("AccountId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("MLDShopping_Admin.Entities.AccountPermission", b =>
                {
                    b.Property<int>("AccountPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<string>("PermissionId");

                    b.Property<int?>("PermissionId1");

                    b.HasKey("AccountPermissionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PermissionId1");

                    b.ToTable("AccountPermission");
                });

            modelBuilder.Entity("MLDShopping_Admin.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("PermissionId");

                    b.HasIndex("AccountId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("MLDShopping_Admin.Entities.AccountPermission", b =>
                {
                    b.HasOne("MLDShopping_Admin.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MLDShopping_Admin.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId1");
                });

            modelBuilder.Entity("MLDShopping_Admin.Entities.Permission", b =>
                {
                    b.HasOne("MLDShopping_Admin.Entities.Account")
                        .WithMany("Permissions")
                        .HasForeignKey("AccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
